/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as Page_researchRouteImport } from './routes/page_research'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as CreateaRouteImport } from './routes/createa'
import { Route as Brand_v1RouteImport } from './routes/brand_v1'
import { Route as Brand_V2RouteImport } from './routes/brand_V2'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const Page_researchRoute = Page_researchRouteImport.update({
  id: '/page_research',
  path: '/page_research',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateaRoute = CreateaRouteImport.update({
  id: '/createa',
  path: '/createa',
  getParentRoute: () => rootRouteImport,
} as any)
const Brand_v1Route = Brand_v1RouteImport.update({
  id: '/brand_v1',
  path: '/brand_v1',
  getParentRoute: () => rootRouteImport,
} as any)
const Brand_V2Route = Brand_V2RouteImport.update({
  id: '/brand_V2',
  path: '/brand_V2',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/artifacts': typeof ArtifactsRoute
  '/brand': typeof BrandRoute
  '/brand_V2': typeof Brand_V2Route
  '/brand_v1': typeof Brand_v1Route
  '/createa': typeof CreateaRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/page_research': typeof Page_researchRoute
  '/planner': typeof PlannerRoute
  '/products': typeof ProductsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/artifacts': typeof ArtifactsRoute
  '/brand': typeof BrandRoute
  '/brand_V2': typeof Brand_V2Route
  '/brand_v1': typeof Brand_v1Route
  '/createa': typeof CreateaRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/page_research': typeof Page_researchRoute
  '/planner': typeof PlannerRoute
  '/products': typeof ProductsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/artifacts': typeof ArtifactsRoute
  '/brand': typeof BrandRoute
  '/brand_V2': typeof Brand_V2Route
  '/brand_v1': typeof Brand_v1Route
  '/createa': typeof CreateaRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/page_research': typeof Page_researchRoute
  '/planner': typeof PlannerRoute
  '/products': typeof ProductsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/artifacts'
    | '/brand'
    | '/brand_V2'
    | '/brand_v1'
    | '/createa'
    | '/integrations'
    | '/knowledge'
    | '/page_research'
    | '/planner'
    | '/products'
    | '/research'
    | '/settings'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/artifacts'
    | '/brand'
    | '/brand_V2'
    | '/brand_v1'
    | '/createa'
    | '/integrations'
    | '/knowledge'
    | '/page_research'
    | '/planner'
    | '/products'
    | '/research'
    | '/settings'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/artifacts'
    | '/brand'
    | '/brand_V2'
    | '/brand_v1'
    | '/createa'
    | '/integrations'
    | '/knowledge'
    | '/page_research'
    | '/planner'
    | '/products'
    | '/research'
    | '/settings'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ArtifactsRoute: typeof ArtifactsRoute
  BrandRoute: typeof BrandRoute
  Brand_V2Route: typeof Brand_V2Route
  Brand_v1Route: typeof Brand_v1Route
  CreateaRoute: typeof CreateaRoute
  IntegrationsRoute: typeof IntegrationsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  Page_researchRoute: typeof Page_researchRoute
  PlannerRoute: typeof PlannerRoute
  ProductsRoute: typeof ProductsRoute
  ResearchRoute: typeof ResearchRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page_research': {
      id: '/page_research'
      path: '/page_research'
      fullPath: '/page_research'
      preLoaderRoute: typeof Page_researchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/createa': {
      id: '/createa'
      path: '/createa'
      fullPath: '/createa'
      preLoaderRoute: typeof CreateaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand_v1': {
      id: '/brand_v1'
      path: '/brand_v1'
      fullPath: '/brand_v1'
      preLoaderRoute: typeof Brand_v1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand_V2': {
      id: '/brand_V2'
      path: '/brand_V2'
      fullPath: '/brand_V2'
      preLoaderRoute: typeof Brand_V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ArtifactsRoute: ArtifactsRoute,
  BrandRoute: BrandRoute,
  Brand_V2Route: Brand_V2Route,
  Brand_v1Route: Brand_v1Route,
  CreateaRoute: CreateaRoute,
  IntegrationsRoute: IntegrationsRoute,
  KnowledgeRoute: KnowledgeRoute,
  Page_researchRoute: Page_researchRoute,
  PlannerRoute: PlannerRoute,
  ProductsRoute: ProductsRoute,
  ResearchRoute: ResearchRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
