# Generated by Django 6.0.4 on 2026-05-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Tên tài liệu"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="ai_knowledge/%Y/%m/", verbose_name="File gốc"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xử lý"),
                            ("processing", "Đang nạp dữ liệu..."),
                            ("completed", "Đã sẵn sàng"),
                            ("failed", "Lỗi hệ thống"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "chunk_count",
                    models.IntegerField(default=0, verbose_name="Số đoạn đã cắt"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Bộ tri thức",
                "verbose_name_plural": "Các bộ tri thức",
            },
        ),
    ]
