# Generated by Django 6.0.4 on 2026-05-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsource',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bộ tri thức', 'verbose_name_plural': 'Các bộ tri thức'},
        ),
        migrations.AddField(
            model_name='documentsource',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='documentsource',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Lỗi xử lý'),
        ),
        migrations.AddField(
            model_name='documentsource',
            name='file_size',
            field=models.BigIntegerField(default=0, verbose_name='Kích thước file'),
        ),
        migrations.AddField(
            model_name='documentsource',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentsource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documentsource',
            name='vector_doc_id',
            field=models.CharField(blank=True, help_text='ID document trong vector database', max_length=255, null=True, verbose_name='Vector Document ID'),
        ),
        migrations.AlterField(
            model_name='documentsource',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang nạp dữ liệu...'), ('completed', 'Đã sẵn sàng'), ('failed', 'Lỗi hệ thống')], db_index=True, default='pending', max_length=20),
        ),
    ]
