# Generated by Django 6.0.5 on 2026-05-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0005_remove_documentnode_document_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentsource",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="documentsource",
            name="file_size",
        ),
        migrations.AddField(
            model_name="documentsource",
            name="chunk_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="documentsource",
            name="file",
            field=models.FileField(upload_to="knowledge/%Y/%m/"),
        ),
    ]
